language: php
php:
  - 5.4
  - 5.3
  - hhvm
env:
  - MATH_BIGINTEGER_MODE=INTERNAL
  - MATH_BIGINTEGER_MODE=GMP
  - MATH_BIGINTEGER_MODE=BCMATH

before_script:
  - composer install --dev

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text
